# Site settings
name: Reserved Place of Copenhag
title: Reserved Place of Copenhag
email: 
author: Copenhag
url: 
resume_site: 
github: 
baseurl: ''
description: 
meta_description: 
motto: 
banner: 

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: kevinhuang88

# Build settings
markdown: kramdown
repository: kevinhuang88/kevinhuang88.github.io
future: true



